import 'package:flutter/material.dart';

class MedicationScreen extends StatelessWidget {
  final List<Map<String, dynamic>> medications = [
    {
      'name': 'Adalat (Nifedipine)',
      'category': 'C',
      'use': 'Calcium channel blocker for hypertension/preterm labor',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Aldomet (Methyldopa)',
      'category': 'B',
      'use': 'Safe for hypertension',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food. Taking it with food may help reduce dizziness or stomach upset.',
      'additional_info': '',
    },
    {
      'name': 'Amaryl (Glimepiride)',
      'category': 'C',
      'use': 'Type 2 diabetes',
      'dose': '1-4 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Type 1 diabetes. Side effects: Hypoglycemia.',
    },
    {
      'name': 'Amoxil (Amoxicillin)',
      'category': 'B',
      'use': 'Safe antibiotic for infections',
      'dose': '500 mg every 8 hours',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Apresoline (Hydralazine)',
      'category': 'C',
      'use': 'Hypertensive emergencies (IV)',
      'dose': 'Not specified',
      'when_to_take': 'Typically administered intravenously in emergency situations, so food intake is not relevant.',
      'additional_info': '',
    },
    {
      'name': 'Augmentin (Amoxicillin + Clavulanic Acid)',
      'category': 'B',
      'use': 'Bacterial infections',
      'dose': '500 mg every 8 hours',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Penicillin allergy. Side effects: Diarrhea, rash.',
    },
    {
      'name': 'Azelaic Acid Cream',
      'category': 'B',
      'use': 'Acne treatment',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Safe in pregnancy; reduces inflammation and bacteria.',
    },
    {
      'name': 'Bacitracin Ointment',
      'category': 'B',
      'use': 'Antibiotic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Used for minor skin infections; considered safe topically.',
    },
    {
      'name': 'Benadryl (Diphenhydramine)',
      'category': 'B',
      'use': 'Sedating antihistamine. Use with caution late pregnancy',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food. Taking it with food may help prevent stomach upset.',
      'additional_info': '',
    },
    {
      'name': 'Benzoyl Peroxide Cream',
      'category': 'C',
      'use': 'Acne treatment',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Limited systemic absorption; use cautiously.',
    },
    {
      'name': 'Betamethasone Dipropionate Cream',
      'category': 'C',
      'use': 'Anti-inflammatory corticosteroid',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Potent steroid; use cautiously during pregnancy especially on large areas.',
    },
    {
      'name': 'Calamine Lotion',
      'category': 'Not Classified',
      'use': 'Skin protectant and anti-itch',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Considered safe; used for mild irritation.',
    },
    {
      'name': 'Calcipotriol Cream',
      'category': 'C',
      'use': 'Psoriasis treatment',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Use only if benefits outweigh risks.',
    },
    {
      'name': 'Calcium + Vitamin D',
      'category': 'A (High Vitamin D may be Category C)',
      'use': 'Essential for bone health',
      'dose': 'Calcium: 1000–1200 mg/day, Vitamin D: 400–1000 IU/day',
      'when_to_take': 'Calcium: Can be taken with food to improve absorption. Vitamin D: Better with a meal containing fat.',
      'additional_info': 'Vital for fetal bones, maternal systems, and reduces preeclampsia risk.',
    },
    {
      'name': 'Canesten (Clotrimazole – topical)',
      'category': 'B',
      'use': 'Vaginal yeast infections',
      'dose': 'Not specified',
      'when_to_take': 'Applied vaginally, so food intake is not relevant.',
      'additional_info': '',
    },
    {
      'name': 'Capsaicin Cream',
      'category': 'C',
      'use': 'Pain relief',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Avoid in pregnancy due to limited safety data.',
    },
    {
      'name': 'Cardura (Doxazosin)',
      'category': 'C',
      'use': 'Hypertension, BPH',
      'dose': '1-8 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Dizziness, fatigue.',
    },
    {
      'name': 'Choriomon / Pregnyl (hCG injections)',
      'category': 'C',
      'use': 'Stimulates corpus luteum to maintain progesterone',
      'dose': '5000–10000 IU every 3–5 days. Requires monitoring',
      'when_to_take': 'Injected, so food intake is not relevant for administration.',
      'additional_info': 'Mimics LH, supports corpus luteum to produce progesterone until placenta takes over.',
    },
    {
      'name': 'Cialis (Tadalafil)',
      'category': 'B',
      'use': 'Erectile dysfunction',
      'dose': '10 mg before sexual activity',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Nitrate use. Side effects: Headache.',
    },
    {
      'name': 'Cipralex (Escitalopram)',
      'category': 'C',
      'use': 'Depression',
      'dose': '10-20 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: MAO inhibitor use. Side effects: Nausea.',
    },
    {
      'name': 'Claritin (Loratadine)',
      'category': 'B',
      'use': 'Non-sedating antihistamine. Safe during pregnancy',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Clexane (Enoxaparin) / Heparin',
      'category': 'B',
      'use': 'Anticoagulants for thrombophilia',
      'dose': 'Not specified',
      'when_to_take': 'Injected, so food intake is not relevant for administration.',
      'additional_info': 'Don\'t cross the placenta, safe with monitoring.',
    },
    {
      'name': 'Clindamycin Cream',
      'category': 'B',
      'use': 'Antibiotic for acne',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Safe topically in pregnancy.',
    },
    {
      'name': 'Clotrimazole Cream',
      'category': 'B',
      'use': 'Antifungal',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Treats fungal infections like ringworm; safe for topical use in pregnancy.',
    },
    {
      'name': 'Colace (Docusate Sodium)',
      'category': 'C',
      'use': 'Stool softener',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Crestor (Rosuvastatin)',
      'category': 'X',
      'use': 'Hypercholesterolemia',
      'dose': '5-40 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Liver disease. Side effects: Muscle pain.',
    },
    {
      'name': 'Crinone (Progesterone)',
      'category': 'B (vaginal) / D (oral high dose)',
      'use': 'Luteal phase support',
      'dose': '200–400 mg/day (vaginal)',
      'when_to_take': 'Vaginal gel, so food intake is not relevant for administration.',
      'additional_info': 'Bioadhesive vaginal gel for sustained release directly to uterus, less systemic absorption.',
    },
    {
      'name': 'Cytotec (Misoprostol)',
      'category': 'X',
      'use': 'Abortion, gastric ulcers (off-label)',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with food to reduce GI side effects.',
      'additional_info': '',
    },
    {
      'name': 'Danol (Danazol)',
      'category': 'X',
      'use': 'Endometriosis. Causes fetal virilization',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Dexamethasone',
      'category': 'C',
      'use': 'Inflammation',
      'dose': '0.75-9 mg daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Fungal infections. Side effects: Immunosuppression.',
    },
    {
      'name': 'Diclegis (Doxylamine + Vitamin B6)',
      'category': 'A',
      'use': 'Specifically for nausea/vomiting in pregnancy',
      'dose': 'Not specified',
      'when_to_take': 'Often recommended to take on an empty stomach at bedtime to alleviate morning sickness symptoms.',
      'additional_info': '',
    },
    {
      'name': 'Diclofenac',
      'category': 'C (1st & 2nd trimester), D (3rd trimester)',
      'use': 'Pain, inflammation',
      'dose': '50 mg two to three times daily',
      'when_to_take': 'Can be taken with food to reduce GI upset.',
      'additional_info': 'Contraindications: Peptic ulcer, bleeding disorders. Side effects: GI upset, headache.',
    },
    {
      'name': 'Dilatrend (Carvedilol)',
      'category': 'C',
      'use': 'Hypertension, heart failure',
      'dose': '6.25-25 mg twice daily',
      'when_to_take': 'Can be taken with food to reduce side effects.',
      'additional_info': 'Contraindications: Severe bradycardia. Side effects: Fatigue.',
    },
    {
      'name': 'Duphaston (Dydrogesterone)',
      'category': 'B',
      'use': 'Supports endometrial function in progesterone deficiency',
      'dose': '10 mg, 2–3 times/day. Safe up to 12 weeks of pregnancy',
      'when_to_take': 'Can be taken with or without food. Taking it with food may help reduce any potential stomach upset.',
      'additional_info': 'Retro-progesterone, high oral bioavailability, no masculinizing effects on female fetus or androgenic side effects for mother.',
    },
    {
      'name': 'Ergometrine (Methergine)',
      'category': 'X',
      'use': 'Postpartum bleeding control',
      'dose': 'Not specified',
      'when_to_take': 'Typically administered in a hospital setting.',
      'additional_info': '',
    },
    {
      'name': 'Erythrocin (Erythromycin)',
      'category': 'B',
      'use': 'Alternative antibiotic for penicillin allergy',
      'dose': 'Not specified',
      'when_to_take': 'Best taken on an empty stomach (1 hour before or 2 hours after meals). Can be taken with food if it causes stomach upset.',
      'additional_info': '',
    },
    {
      'name': 'Erythromycin Cream',
      'category': 'B',
      'use': 'Antibiotic for acne and infections',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Safe topically in pregnancy.',
    },
    {
      'name': 'Estrogen + Progestin Combos (e.g., Cyclo-Proginova)',
      'category': 'X',
      'use': 'Hormonal therapy or contraceptives accidentally taken during pregnancy',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Ferrous Sulfate (Iron)',
      'category': 'A',
      'use': 'Prevention and treatment of iron-deficiency anemia',
      'dose': '30–60 mg elemental iron daily',
      'when_to_take': 'Best taken on an empty stomach. Can be taken with food if it causes stomach upset. Absorption enhanced by Vitamin C.',
      'additional_info': 'Absorption enhanced by Vitamin C.',
    },
    {
      'name': 'Folic Acid',
      'category': 'A',
      'use': 'Prevents neural tube defects',
      'dose': '400–800 mcg/day (up to 5 mg in high-risk cases). Recommended preconception and in 1st trimester',
      'when_to_take': 'Can be taken with or without food. Taking it with food might be preferable if you experience any mild nausea.',
      'additional_info': 'Synthetic form of folate (Vitamin B9), crucial for DNA synthesis, repair, and methylation during rapid cell division.',
    },
    {
      'name': 'Fusidic Acid Cream',
      'category': 'B',
      'use': 'Antibiotic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Effective for bacterial skin infections; topical use safe in pregnancy.',
    },
    {
      'name': 'G.C. Mol Effervescent',
      'category': 'Paracetamol: B, Guaifenesin & Vitamin C: Not specifically classified',
      'use': 'Symptomatic relief in adults: fever, headache, sore throat, common cold, and influenza. Guaifenesin acts as an expectorant to loosen mucus. Vitamin C supports immune function.',
      'dose': '1–2 sachets every 4–6 hours, up to 3–4 sachets per day',
      'when_to_take': 'Dissolve in water before use. Can be taken with or without food.',
      'additional_info': 'Comes in effervescent sachets; flavor helps soothe the throat. Storage: Keep below 25 °C, away from moisture and direct sunlight.',
      'active_ingredients': 'Paracetamol (Acetaminophen) 325 mg, Guaifenesin 100 mg, Vitamin C 250 mg',
      'contraindications': 'Hypersensitivity to any component. Use caution in pregnancy and breastfeeding—consult physician.',
      'side_effects': 'Paracetamol overdose → hepatotoxicity. Guaifenesin → mild gastrointestinal upset. Vitamin C at high doses → may cause diarrhea or stomach cramps.',
    },
    {
      'name': 'Gas-X (Simethicone)',
      'category': 'C',
      'use': 'Gas relief, generally safe',
      'dose': 'Not specified',
      'when_to_take': 'Taken as needed, usually after meals or at bedtime.',
      'additional_info': '',
    },
    {
      'name': 'Glucophage (Metformin)',
      'category': 'B',
      'use': 'Type 2 diabetes',
      'dose': '500-1000 mg twice daily',
      'when_to_take': 'Can be taken with food to reduce GI upset.',
      'additional_info': 'Contraindications: Renal impairment. Side effects: GI upset.',
    },
    {
      'name': 'Hydrocortisone Cream',
      'category': 'C',
      'use': 'Anti-inflammatory, corticosteroid',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Used for eczema and dermatitis; low potency; relatively safe but avoid prolonged use in pregnancy.',
    },
    {
      'name': 'Imiquimod Cream',
      'category': 'C',
      'use': 'Immunomodulator for warts and skin cancers',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Avoid in pregnancy unless benefits outweigh risks.',
    },
    {
      'name': 'Imodium (Loperamide)',
      'category': 'C',
      'use': 'For diarrhea, use cautiously',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Imutrexate (Methotrexate)',
      'category': 'X',
      'use': 'Cancer, autoimmune, ectopic pregnancy. Teratogenic',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Keflex (Cephalexin)',
      'category': 'B',
      'use': 'Bacterial infections',
      'dose': '250-500 mg every 6 hours',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Cephalosporin allergy. Side effects: Diarrhea, nausea.',
    },
    {
      'name': 'Ketoconazole Cream',
      'category': 'C',
      'use': 'Antifungal',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Treats fungal infections; limited data for pregnancy.',
    },
    {
      'name': 'Lasix (Furosemide)',
      'category': 'C',
      'use': 'Diuretic, for severe cases only',
      'dose': '20-80 mg daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Levitra (Vardenafil)',
      'category': 'B',
      'use': 'Erectile dysfunction',
      'dose': '10 mg before sexual activity',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Nitrate use. Side effects: Flushing.',
    },
    {
      'name': 'Lidocaine Cream',
      'category': 'B',
      'use': 'Local anesthetic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Minimal absorption; generally safe topically.',
    },
    {
      'name': 'Lipitor (Atorvastatin)',
      'category': 'X',
      'use': 'Hypercholesterolemia',
      'dose': '10-40 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Liver disease. Side effects: Muscle pain.',
    },
    {
      'name': 'Low-Dose Aspirin (Acetylsalicylic Acid / Baby Aspirin)',
      'category': 'C (early) / D (3rd trimester)',
      'use': 'Improves placental circulation in high-risk pregnancies',
      'dose': '75–100 mg/day. Usually stopped before the 3rd trimester',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Inhibits COX enzyme, reduces thromboxane A2, decreases platelet aggregation, improves uteroplacental blood flow.',
    },
    {
      'name': 'Marevan / Coumadin / Warfarin',
      'category': 'X (except limited 2nd trimester use)',
      'use': 'Anticoagulation, high fetal risk',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Metamucil / FiberCon (Fiber supplements)',
      'category': 'A',
      'use': 'Bulk-forming laxatives',
      'dose': 'Not specified',
      'when_to_take': 'Usually taken with a full glass of water, and can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Metronidazole Cream',
      'category': 'B',
      'use': 'Antibiotic and antiprotozoal (rosacea)',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Considered safe topically in pregnancy.',
    },
    {
      'name': 'Miconazole Cream',
      'category': 'C',
      'use': 'Antifungal',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Used for fungal infections; topical use considered safe.',
    },
    {
      'name': 'Mifepristone',
      'category': 'X',
      'use': 'Medical abortion',
      'dose': 'Not specified',
      'when_to_take': 'Administered under medical supervision.',
      'additional_info': '',
    },
    {
      'name': 'Motilium (Domperidone)',
      'category': 'C',
      'use': 'Nausea, vomiting, gastroparesis',
      'dose': '10 mg three times daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Prolactin-dependent tumors, cardiac arrhythmias. Side effects: Dry mouth, abdominal cramps.',
    },
    {
      'name': 'Mucinex (Guaifenesin)',
      'category': 'C',
      'use': 'Expectorant. Avoid in 1st trimester unless necessary',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food. Taking it with food might help if it causes any stomach upset.',
      'additional_info': '',
    },
    {
      'name': 'Mupirocin Cream',
      'category': 'B',
      'use': 'Antibiotic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Used for bacterial skin infections; minimal systemic absorption.',
    },
    {
      'name': 'Neomycin Sulfate Cream',
      'category': 'D',
      'use': 'Antibiotic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Risk of toxicity systemically; topical use usually minimal risk but caution advised.',
    },
    {
      'name': 'Nexium (Esomeprazole)',
      'category': 'B',
      'use': 'GERD',
      'dose': '20-40 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Diarrhea.',
    },
    {
      'name': 'Normix (Rifaximin)',
      'category': 'C',
      'use': 'Traveler’s diarrhea',
      'dose': '200 mg three times daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Severe hepatic impairment. Side effects: Nausea.',
    },
    {
      'name': 'Norvasc (Amlodipine)',
      'category': 'C',
      'use': 'Hypertension, angina',
      'dose': '5-10 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Edema, dizziness.',
    },
    {
      'name': 'Panadol / Tylenol (Paracetamol / Acetaminophen)',
      'category': 'B',
      'use': 'First-line for pain and fever',
      'dose': '500–1000 mg every 4–6 hours (max 4 g/day). Safe all trimesters',
      'when_to_take': 'Can be taken with or without food. If you experience stomach upset, taking it with food might help.',
      'additional_info': '',
    },
    {
      'name': 'Pepcid (Famotidine)',
      'category': 'B',
      'use': 'H2 blocker for GERD',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Pimecrolimus Cream',
      'category': 'C',
      'use': 'Immunomodulator for eczema',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Safety not well established in pregnancy; use only if benefits outweigh risks.',
    },
    {
      'name': 'Plavix (Clopidogrel)',
      'category': 'B',
      'use': 'Prevention of clots',
      'dose': '75 mg once daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Active bleeding. Side effects: Bleeding.',
    },
    {
      'name': 'Proluton Depot (Hydroxyprogesterone Caproate)',
      'category': 'D',
      'use': 'Prevents preterm labor in high-risk women',
      'dose': '250 mg IM weekly from week 16–36. Reserved for selected cases',
      'when_to_take': 'Injected, so food intake is not relevant.',
      'additional_info': 'Synthetic, long-acting progesterone, depot formulation for slow release.',
    },
    {
      'name': 'Proscar / Avodart (Finasteride, Dutasteride)',
      'category': 'X',
      'use': 'BPH, baldness. Causes fetal feminization abnormalities',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Retinoid Cream (Tretinoin)',
      'category': 'C',
      'use': 'Acne treatment',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Avoid in pregnancy due to teratogenic risk.',
    },
    {
      'name': 'Roaccutane / Netlook (Isotretinoin)',
      'category': 'X',
      'use': 'Severe acne. Causes severe birth defects',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with food to enhance absorption.',
      'additional_info': '',
    },
    {
      'name': 'Robitussin DM (Dextromethorphan)',
      'category': 'C',
      'use': 'Cough suppressant. Use if needed',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Salicylic Acid Cream',
      'category': 'C',
      'use': 'Keratolytic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Use with caution; avoid large areas or high concentration during pregnancy.',
    },
    {
      'name': 'Septrin (Trimethoprim + Sulfamethoxazole)',
      'category': 'D',
      'use': 'UTIs',
      'dose': 'Double-strength tablet twice daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Sulfa allergy. Side effects: Rash.',
    },
    {
      'name': 'Silver Sulfadiazine Cream',
      'category': 'C',
      'use': 'Antimicrobial for burns',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Sulfonamide component may have risks; avoid in late pregnancy.',
    },
    {
      'name': 'Sulfur Cream',
      'category': 'Not Classified',
      'use': 'Antibacterial and keratolytic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Generally safe, limited data.',
    },
    {
      'name': 'Syntocinon / Pitocin (Oxytocin)',
      'category': 'X (if not in labor)',
      'use': 'Induce labor under supervision',
      'dose': 'Not specified',
      'when_to_take': 'Typically administered intravenously in a hospital setting, so food intake is not relevant.',
      'additional_info': '',
    },
    {
      'name': 'Syntometrine (Oxytocin + Ergometrine)',
      'category': 'X',
      'use': 'Postpartum bleeding control',
      'dose': 'Not specified',
      'when_to_take': 'Typically administered in a hospital setting.',
      'additional_info': '',
    },
    {
      'name': 'Synthroid (Levothyroxine)',
      'category': 'A',
      'use': 'Hypothyroidism',
      'dose': '25-200 mcg once daily',
      'when_to_take': 'Best taken on an empty stomach, at least 30 minutes before food.',
      'additional_info': 'Contraindications: Untreated thyrotoxicosis. Side effects: Palpitations, weight loss.',
    },
    {
      'name': 'Tacrolimus Cream',
      'category': 'C',
      'use': 'Immunomodulator',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Similar to pimecrolimus; caution in pregnancy.',
    },
    {
      'name': 'Telfast (Fexofenadine)',
      'category': 'C',
      'use': 'Allergies',
      'dose': '120 mg once or twice daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Headache.',
    },
    {
      'name': 'Temazepam, Triazolam',
      'category': 'D',
      'use': 'Insomnia. Teratogenic risk',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Thalix (Thalidomide)',
      'category': 'X',
      'use': 'Multiple myeloma, leprosy. Causes severe limb deformities',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Tolnaftate Cream',
      'category': 'C',
      'use': 'Antifungal for athlete’s foot',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Limited pregnancy data; use cautiously.',
    },
    {
      'name': 'Topical Phenylephrine (Preparation H)',
      'category': 'Not specified',
      'use': 'Vasoconstrictor, relieves discomfort',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': '',
    },
    {
      'name': 'Trandate (Labetalol)',
      'category': 'C',
      'use': 'Alpha/beta-blocker, used in preeclampsia',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with food to enhance absorption and reduce the risk of orthostatic hypotension.',
      'additional_info': '',
    },
    {
      'name': 'Triamcinolone Acetonide Cream',
      'category': 'C',
      'use': 'Anti-inflammatory corticosteroid',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Potent steroid; caution in pregnancy.',
    },
    {
      'name': 'Tums (Calcium Carbonate)',
      'category': 'B',
      'use': 'Antacid for occasional heartburn',
      'dose': 'Not specified',
      'when_to_take': 'Taken as needed, usually after meals or when heartburn symptoms occur.',
      'additional_info': '',
    },
    {
      'name': 'Urea Cream',
      'category': 'Not Classified',
      'use': 'Moisturizer and keratolytic',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Generally safe.',
    },
    {
      'name': 'Utrogestan (Progesterone)',
      'category': 'B (vaginal) / D (oral high dose)',
      'use': 'Luteal phase support',
      'dose': '200–400 mg/day (vaginal)',
      'when_to_take': 'Vaginal, so food intake is not relevant for administration.',
      'additional_info': 'Micronized progesterone, enhances absorption, vaginal route preferred to minimize systemic side effects like drowsiness.',
    },
    {
      'name': 'Vasodilan (Isoxsuprine)',
      'category': 'C',
      'use': 'Beta-agonist, rarely used',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Ventolin (Salbutamol)',
      'category': 'C',
      'use': 'Asthma',
      'dose': '2 puffs every 4-6 hours',
      'when_to_take': 'Inhaled, so food intake is not relevant.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Tremor.',
    },
    {
      'name': 'Vitamin B6 (Pyridoxine)',
      'category': 'A',
      'use': 'Morning sickness relief',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
    {
      'name': 'Voltaren (Diclofenac)',
      'category': 'C (1st & 2nd trimester), D (3rd trimester)',
      'use': 'Pain and inflammation',
      'dose': '50 mg two to three times daily',
      'when_to_take': 'Can be taken with food to reduce GI upset.',
      'additional_info': 'Contraindications: Peptic ulcer. Side effects: GI upset.',
    },
    {
      'name': 'Witch Hazel Pads (Tucks)',
      'category': 'Not specified',
      'use': 'Astringent and anti-inflammatory',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': '',
    },
    {
      'name': 'Xanax (Alprazolam)',
      'category': 'D',
      'use': 'Anxiety',
      'dose': '0.25-0.5 mg three times daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Narrow-angle glaucoma. Side effects: Drowsiness.',
    },
    {
      'name': 'Xarelto (Rivaroxaban)',
      'category': 'C',
      'use': 'Thromboembolism prevention',
      'dose': '10-20 mg once daily',
      'when_to_take': 'Can be taken with food to enhance absorption.',
      'additional_info': 'Contraindications: Bleeding. Side effects: Anemia.',
    },
    {
      'name': 'Yutopar (Ritodrine)',
      'category': 'B',
      'use': 'Inhibits uterine contractions',
      'dose': 'Not specified',
      'when_to_take': 'Dosage and timing are typically determined by a healthcare provider in a hospital setting.',
      'additional_info': '',
    },
    {
      'name': 'Zantac (Ranitidine)',
      'category': 'B',
      'use': 'GERD',
      'dose': '150 mg twice daily',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': 'Contraindications: Hypersensitivity. Side effects: Headache.',
    },
    {
      'name': 'Zinc Oxide Ointment',
      'category': 'Not Classified',
      'use': 'Skin barrier cream',
      'dose': 'Not specified',
      'when_to_take': 'Applied topically, so food intake is not relevant.',
      'additional_info': 'Safe for skin protection.',
    },
    {
      'name': 'Zyrtec (Cetirizine)',
      'category': 'B',
      'use': 'Non-sedating antihistamine. Safe during pregnancy',
      'dose': 'Not specified',
      'when_to_take': 'Can be taken with or without food.',
      'additional_info': '',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [Colors.pink[100]!, Colors.orange[50]!],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(
                  'Medication Information',
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: Colors.pink[800],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              Expanded(
                child: ListView.builder(
                  padding: const EdgeInsets.all(8.0),
                  itemCount: medications.length,
                  itemBuilder: (context, index) {
                    final medication = medications[index];
                    return Card(
                      elevation: 4,
                      margin: const EdgeInsets.symmetric(vertical: 8.0),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: ListTile(
                        title: Text(
                          medication['name']!,
                          style: const TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        onTap: () {
                          showDialog(
                            context: context,
                            builder: (context) => AlertDialog(
                              title: Text(medication['name']!),
                              content: SingleChildScrollView(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Text('Category: ${medication['category']!}'),
                                    const SizedBox(height: 10),
                                    Text('Use: ${medication['use']!}'),
                                    const SizedBox(height: 10),
                                    Text('Dose: ${medication['dose']!}'),
                                    const SizedBox(height: 10),
                                    Text('When to Take: ${medication['when_to_take']!}'),
                                    const SizedBox(height: 10),
                                    Text('Additional Info: ${medication['additional_info']!}'),
                                    if (medication.containsKey('active_ingredients')) ...[
                                      const SizedBox(height: 10),
                                      Text('Active Ingredients: ${medication['active_ingredients']!}'),
                                    ],
                                    if (medication.containsKey('contraindications')) ...[
                                      const SizedBox(height: 10),
                                      Text('Contraindications: ${medication['contraindications']!}'),
                                    ],
                                    if (medication.containsKey('side_effects')) ...[
                                      const SizedBox(height: 10),
                                      Text('Side Effects: ${medication['side_effects']!}'),
                                    ],
                                    if (medication.containsKey('storage')) ...[
                                      const SizedBox(height: 10),
                                      Text('Storage: ${medication['storage']!}'),
                                    ],
                                  ],
                                ),
                              ),
                              actions: [
                                TextButton(
                                  onPressed: () => Navigator.pop(context),
                                  child: const Text('Close'),
                                ),
                              ],
                            ),
                          );
                        },
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}